x86_64/Dockerfile, x86_64/Makefile
I made a PR to download the binary from github directly. This way it does not depends on which is the stable crystal package published in debian.
=> Use github releases to download a specific initial version

x86_64/Dockerfile-fpm, x86_64/Makefile
I try using ruby:2.4-alpine but the tar in alpine was complaining about --owner=0 option.
I split the cache & pull docker flags from build args
The temp directory now is fixed to /tmp/crystal, I've no strong opinion here, it just felt simpler (meanwhile there was a miss typed $$tmpdir -> $$tempdir in rpm target that now is "fixed")
=> Use fpm via docker

omnibus/Gemfile
Will silence warnings like:
>The git source `git://github.com/XXX/YYY.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
See https://github.com/bundler/bundler/blob/1e8ce587798edcc75f72cb89eea5a2a425bb579c/lib/bundler/dsl.rb#L277-L289
=> Always use https protocol for dependencies fetched from GitHub

omnibus/Gemfile, omnibus/Gemfile.lock
Since #6 started to be used for nightly builds the osx build was failing https://circleci.com/gh/crystal-lang/crystal/5719
This changes fixed that https://circleci.com/gh/crystal-lang/crystal/5760.
The alternative would be to rollback #6.
@Sija it seems that when the PR was sent the `bundle` command was not run to update the Gemfile.lock
It's a bit ugly that revision and ref is present in Gemfile.lock, but it seems to be the bundler way.
=> Fix Gemfile in order to keep omnibus 5.5.0 compatible gems

linux/Dockerfile
Man pages for shards are missing from the package build, see https://github.com/crystal-lang/shards/issues/189#issuecomment-381178756.
=> Add manpages for shards

linux/Makefile
This PR fixes https://github.com/crystal-lang/crystal/issues/4680 and also adds the libz-dev dependency that is used while running `shards build`
=> fix issue https://github.com/crystal-lang/crystal/issues/4680

linux/Makefile
Ref: https://github.com/crystal-lang/distribution-scripts/pull/19#issuecomment-428331160
Build is already happy at https://circleci.com/workflow-run/435fcdcc-16a0-497b-be2a-c09356eaa61a
=> Use pkg-config instead of pkgconf package

linux/Dockerfile-fpm
Rubygems 3 is out and shipped in ruby:2.4/2.5 docker images by default.
Rubygems 3 does no longer support --no-ri --no-rdoc options and nightly builds are failing.
After this PR an update in crystal will be needed and we can include the latest changes also.
=> Remove --no-ri --no-rdoc options

linux/Dockerfile
Related to #33 .
Sometimes the touch leave the same date as the cc output. The sleep should fix that.
I added ldd output to have some additional manual checks during the build.
I'm not sure if this will solve 100% of the issues, but it reduces the chances and the logs have additional diagnosis information.
Maintenance build at https://circleci.com/workflow-run/e2779fd7-c51c-4b53-9e61-a36db574e779
=> Add ldd output and wait before touch

.gitignore, snapcraft/Makefile, snapcraft/README.md, snapcraft/crystal-snap-wrapper, snapcraft/snap/local/snapcraft.yaml.tpl
The maintenance and tagged builds are already stressed in 
* https://circleci.com/workflow-run/88f4c4a1-7360-4b71-84ff-5cd19e7fb6d0
* https://circleci.com/workflow-run/9a38150d-836b-4a10-9f9e-8c9b0e442478
This will be used to ship nightly builds to snap.
The snap is built by embedding a known tar.gz that can be a url or a local path
=> Add snap target

docker/Dockerfile, docker/Makefile
Allow parametrized base image for docker image.
Can be used to run the recent compiler before releasing it in the CI.
=> Add targets to build docker images for 32 bits with nightly .deb

docker/alpine.Dockerfile, docker/ubuntu.Dockerfile
* Remove `readline-dev` because `Readline` has been removed from stdlib since Crystal 0.32.0
* Use proper packages providing `libevent`, `openssl` and `zlib` static libraries. (`*-static` packages also install `*-dev` packages
=> Fix APK packages in alpine.Dockerfile

docker/alpine.Dockerfile
Use proper packages providing libevent, openssl and zlib static libraries.
The *-static packages usually also install *-dev packages (except openssl-libs-static).
Followup to #29
=> Fix apk static packages in alpine.Dockerfile

linux/Dockerfile
@RX14 do you have any reason to not include this change proposed in the referenced issue?
Fixes https://github.com/crystal-lang/crystal/issues/8653
It fix the 
```
libgc.a(alloc.o): unrecognized relocation (0x2a) in section `.text'
``` 
issue for me locally
=> Use clang-8 to build linux libgc and libcrystal

darwin/Makefile, docker/ubuntu.Dockerfile, linux/Dockerfile, linux/Makefile, omnibus/config/software/shards.rb
* add check that is statically linked in linux
* install dependencies using previous crystal shards binary
* lld is also included in nightly images to match tagged releases as of crystal-lang/crystal-dist#8
=> Update to shards 0.10.0

linux/Dockerfile
Thanks to https://github.com/crystal-lang/crystal/pull/9238 the workaround is no longer required.
=> Drop workaround for shards compilation in musl

docker/alpine.Dockerfile, docker/ubuntu.Dockerfile, linux/Dockerfile, linux/files/crystal-wrapper, omnibus/config/software/crystal.rb, omnibus/config/templates/crystal/crystal.erb
Thanks to https://github.com/crystal-lang/crystal/pull/9423 we can tidy up the darwin build and wrapper scripts for linux and darwin.
The destination directory for shards `lib` is extracted from compiler binary.
=> Use make update path

linux/Dockerfile, omnibus/config/software/shards.rb
This changes uses `make lib` so it does not require shards to be available.
This is also needed to unlock builds of 1.0.0-dev (since molinillo states `crystal: 0.x`)
=> Avoid requiring shards to build shards

docker/Makefile, docker/alpine.Dockerfile, docker/ubuntu.Dockerfile, docker/ubuntu32.Dockerfile, linux/Dockerfile, linux/Makefile
Ubuntu has dropped i386 architecture in 19.10, so there won't be a 20.04 LTS release for i386.
Also adds a separate Dockerfile for i386 to maintain them separately.
=> Update ubuntu64 Dockerfile to Focal Fossa (20.04 LTS) and LLVM 10

docs/Dockerfile
Enable crystal-lang/crystal#9917
crystal-lang/crystal#10007 adds the same on CI for nightly docs
=> Use canonical base url for generating docs

docker/alpine.Dockerfile, linux/Dockerfile, linux/Makefile
Resolves crystal-lang/crystal#10313
=> Fix alpine Dockerfile to add *-static packages and update to alpine 3.13

docker/alpine.Dockerfile
Otherwise /usr/lib/pkgconfig/libcrypto.pc is missing and LibCrypto / LibSSL will fail to link
Without openssl-dev package
```
/ # crystal eval 'require "openssl"; pp! LibSSL::OPENSSL_VERSION'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: _main.o: in function `__crystal_main':
/usr/share/crystal/src/openssl/lib_ssl.cr:255: undefined reference to `SSL_library_init'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/share/crystal/src/openssl/lib_ssl.cr:255: undefined reference to `SSL_load_error_strings'
/usr/lib/gcc/x86_64-alpine-linux-musl/10.2.1/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/share/crystal/src/openssl/lib_ssl.cr:255: undefined reference to `OPENSSL_add_all_algorithms_noconf' …
```
=> Restore openssl-dev in alpine images

linux/Makefile, omnibus/config/software/shards.rb
This updates shards to 0.14.1
Sample workflow https://app.circleci.com/pipelines/github/crystal-lang/crystal/5428/workflows/6f96f56f-c429-4941-b352-2d2fb4aff1c0
It is based on the commit before #79 because after that PT the crystal binaries end up with some shared libraries linked and the maintenance_release complains https://app.circleci.com/pipelines/github/crystal-lang/crystal/5427/workflows/8f62a04e-4e79-4633-8952-77e7c777dc00 .
=> Update shards to 0.14.1

linux/Dockerfile
Fixes static executable checks which currently fails on alpine 3.13 (see https://github.com/crystal-lang/distribution-scripts/pull/83#issue-589836036).
The reason is explained in https://github.com/crystal-lang/distribution-scripts/pull/87#issuecomment-817865398
Follow-up to #79
=> Fix static executable checks

docker/alpine.Dockerfile, linux/Dockerfile
With https://github.com/crystal-lang/crystal/pull/10463 being merged, `libcrystal.a` no longer exists
=> Remove compilation of libcrystal.a

linux/Dockerfile
Dist builds are currently broken because git checkout is broken by a regression in curl with HTTP/2 (https://daniel.haxx.se/blog/2021/04/14/curl-7-76-1-h2-works-again/).
We're using the curl package from buster-backports which ships curl 7.74.0 (including the regression). This fix temporarily pins to 7.64.0.
@bcardiff Is there a particular reason for using packages from buster-backport for the linux build? If we'd use packages from stable, the bug would not be present.
=> Fix broken linux dist caused by curl regression

packages/scripts/install.sh, packages/test/elementary_os.bats, packages/test/mint.bats
This is a follow-up on #91 improving support for distributions for which OBS does not have a dedicated repository but are based on deb or rpm. The installer then defaults to `Debian_Testing`  and `RHEL_7` repositories.
=> Add support for generic deb/rpm distros

packages/obs-push.sh, packages/obs-setup.sh, packages/scripts/install.sh, packages/support/test-install.sh
Nightlies and unstable builds are published in subprojects on OBS:
* [devel:languages:crystal:nightly](https://build.opensuse.org/package/show/devel:languages:crystal:nightly)
* [devel:languages:crystal:unstable](https://build.opensuse.org/package/show/devel:languages:crystal:unstable)
The script `obs-push.sh` is responsible for pushing the updated build information to OBS.
The installer simply appends `:${CHANNEL}` to the project name.
=> Add support for nightly and unstable builds

omnibus/config/software/libyaml.rb, omnibus/config/software/shards.rb
Removing the dynamic library forces the compiler to pick the static library, removing libyaml as a runtime dependency for shards.
Resolves https://github.com/crystal-lang/crystal/issues/5994
CI run at https://app.circleci.com/pipelines/github/crystal-lang/crystal/5733/workflows/94b82b64-c487-4364-b9f7-424fa591e8ab
=> Omnibus: build libyaml with --disable-shared

processes/crystal-CHANGELOG.md, processes/crystal-release.md, processes/shards-release.md
These checklists have previously been maintained in an external document. Integrating them into this repository makes it easier to discuss changes and keep them up to date, without switching contexts.
The current state represents what was used for the 1.1.0 release. There are already a number of ideas for improvement that will follow later.
=> Add release checklists

packages/support/test-install.sh
The test-install helper script did a full check on base project plus nightly and unstable channels (the latter is unused currently).
This only works for the main project (`devel:languages:crystal`) but not when testing branches (like `home:straight-shoota:branches:devel:languages:crystal`) because the respective projects for nightly and unstable channels are missing.
This patch simplifies the test-install script to only run on a single channel. But CLI arguments are forwarded to the installer. Instead of a single run of `./support/test-install.sh`, you now have to run it several times with different arguments tp get the same result:
```bash
./support/test-install.sh 
./support/test-install.sh --channel=nightly
./support/test-install.sh --channel=unstable # if used
```
Usually you only …
=> Refactor test-install to only check for single project

packages/test/ubuntu.bats, packages/test/ubuntu.i386.bats
Ubuntu 16.04 has reached end of life, so we don't need to run the package tests. They're broken because gpg can't be installed. This should be fixable but is not worth the effort.
We're still providing packages for Ubuntu 16.04 on OBS and they are expected to work.
=> Remove test for Ubuntu 16.04 (reached EOL)

packages/scripts/install.sh, packages/test-install-on-docker.sh
We have versioned packages now on OBS (https://build.opensuse.org/project/show/devel:languages:crystal) for each minor release. This patch adapts the installer script to install these versioned packages when the `--crystal` argument is passed.
=> Update installer to install versioned packages

packages/scripts/install.sh
This patch introduces `--version` as a CLI argument for the installer script because that's a more intuitive name.
The previous argument `--crystal` is still usable, but triggers a deprecation message.
Suggested in https://github.com/crystal-lang/distribution-scripts/pull/112#issuecomment-897112000
=> Installer: Rename `--crystal` argument to `--version`

packages/obs-release.sh, packages/obs-setup.sh, processes/crystal-release.md
Restructures and updated the release checklist.
I think it's much clearer to read with separate sections.
=> Improve release checklist

docker/alpine.Dockerfile, linux/Makefile
Solves [crystal/#10366](https://github.com/crystal-lang/crystal/issues/10366) by partially undoing #79 .
=> Demoting alpine images to alpine 3.12

docker/Makefile, linux/Makefile
This is just a simple enhancement to make `docker/Makefile` and `linux/Makefile` easier to use by having less boilerplate.
=> Add default values for Makefile options

linux/Dockerfile-fpm, linux/Makefile, linux/README.md
The instructions for building deb and rpm packages are no longer in use and can be removed.
We're building packages on OBS now (https://github.com/crystal-lang/crystal/issues/10626).
=> Remove deb and rpm build instructions

linux/Makefile
Fixup for #130
Apparently, adding a comment in that line appends the trailing whitespace to the value.
=> Fix trailing whitespace with PREVIOUS_CRYSTAL_PACKAGE_ITERATION

docker/Makefile, docker/ubuntu.Dockerfile
This patch changes the docker image to install Crystal directly from the generic linux tarball, instead of a debian package. The main purpose is to avoid a dependency on the debian package, which is built in a separate workflow on OBS. 
There should be no significant differences for users.
=> Build ubuntu 64-bit docker image from tar.gz instead of deb

linux/Makefile, snapcraft/Makefile
This patch extracts the first commit from #51. It applies the use of `$@` in Makefiles.
=> Use magic variables in Makefiles

linux/bundled.dockerfile
Building libevent complained about missing `pkg-config`. Not sure why because I'm pretty sure it worked before. But adding it fixes that, so this seems to be the way to go.
=> Add pkg-config to bundled dockerfile

linux/bundled.dockerfile
`ARG` instructions in a Dockerfile need to be repeated for every stage in a multistage build.
I have no idea why this worked when I first tested it, but now it doesn't anymore (https://github.com/crystal-lang/distribution-scripts/pull/143#issuecomment-933596413). Apparently, it should've never worked. https://github.com/crystal-lang/distribution-scripts/pull/102#discussion_r722506331
Successful CI run: https://app.circleci.com/pipelines/github/crystal-lang/crystal/6956/workflows/b013a39d-3bcc-4c07-b3c6-b3cc581649ed/jobs/64412
=> Fix ARG in multistage `bundled.Dockerfile`

linux/bundled.dockerfile, omnibus/config/software/pcre.rb
The server at ftp://ftp.pcre.org has been shut down. This patch changes to a different mirror for downloading libpcre.
CI workflow run: https://app.circleci.com/pipelines/github/crystal-lang/crystal/7227/workflows/f976a68c-4033-4cec-89c4-3cb88b605d23
=> Fix pcre download URL

docker/alpine.Dockerfile, docker/ubuntu.Dockerfile, linux/Dockerfile, omnibus/config/software/crystal.rb, omnibus/config/software/libffi.rb
The upcoming interpreter feature requires libffi (https://github.com/crystal-lang/crystal/pull/11475).
It's only needed in the compiler, so the regular packages don't need to ship the library. It's statically linked into the compiler.
But the build images need it in order to run specs for libffi in CI.
=> Add libffi to build images and in the compiler build workflows

processes/crystal-release.md, processes/scripts/functions.sh, processes/scripts/make-crystal-release.sh, processes/scripts/prepare-crystal-release.sh
This patch adds two scripts that automate parts of Crystal's release workflow.
* `prepare-crystal-release` creates a tracking issue for the release in this repository (#177 was created by that script)
* `make-crystal-release` tags the git commit, pushes it it to GitHub and attaches artifacts when CI is finished (https://github.com/crystal-lang/crystal/releases/tag/1.3.2 was created by that script).
=> Add scripts for Crystal release workflow

linux/bundled.dockerfile, omnibus/config/software/pcre.rb
`nightly_release` workflow is broken on CircleCI https://app.circleci.com/pipelines/github/crystal-lang/crystal/9033/workflows/6c7f40b6-9f7b-463d-9583-da4952037a74
The server at `http://ftp.cs.stanford.edu` is missing pcre tarball.
This patch changes to an official exim mirror for PCRE.
=> Fix libpcre source download

processes/crystal-release.md, processes/scripts/make-crystal-release.sh, processes/scripts/publish-crystal-packages-on-github.sh
* Highlights the automation scripts more as instructions to run them instead of facultative helpers.
* Reorders instructions for documentation after the binary release because we need the binary on GitHub releases for building crystal-book.
* Extracts the step for publishing binary artifacts from CircleCI to GitHub releases into a separate script.
* Clarifies when to use the full version including patch number and when only major and minor.
=> Reorganize crystal release instructions for helper scripts

linux/Dockerfile, linux/Makefile, linux/bundled.dockerfile
This upgrades several components of the Linux build environment:
* alpine:3:12 -> alpine:3.16
* debian:10 -> debian:11
* bdwgc 8.2.0 -> bdwgc 8.2.2
* LLVM 11 -> LLVM 13
Green CI workflow: https://app.circleci.com/pipelines/github/crystal-lang/crystal/9794/workflows/5f762e48-3920-4242-abc1-f4c4685c0a47
Resolves #147
=> Upgrade Linux build environment to LLVM 13

packages/scripts/install.sh
The way this conditional has been implemented seems to be not working on Ubuntu Xenial Releases:
```bash
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
$ command -v gpg
/usr/bin/gpg
$ command -v wget
/usr/bin/wget
$ if [[ -z $(command -v wget &> /dev/null) ]] || [[ -z $(command -v gpg &> /dev/null) ]]; then echo install; else echo pass; fi
install
$ if ! command -v wget &> /dev/null || ! command -v gpg &> /dev/null; then echo install; else echo pass; fi
pass
```
=> Installer: Change dependencies validation

packages/scripts/install.sh
For some reason they seem to have dropped the `openSUSE_Leap_` prefix for releases. Instead of `openSUSE_Leap_15.4`, the repository on OBS is now called just `15.4`.
=> Update `install.sh` for openSUSE

linux/bundled.dockerfile
The additional libs in the bundled tarball (libevent and libpcre) are placed in a subfolder of the lib path that the compiler looks up making them inaccessible.
These files should be placed alongside `libgc` which is also included in the normal tarball.
```console
$ tree crystal-1.7.2-1/lib
crystal-1.7.2-1/lib
└── crystal
├── bin -> ../../bin
├── lib
│   ├── libevent.a
│   ├── libevent_pthreads.a
│   └── libpcre.a
└── libgc.a
4 directories, 4 files
```
=> Fix lib locations in bundled tarball

docker/alpine.Dockerfile, docker/ubuntu.Dockerfile, linux/Makefile, linux/bundled.dockerfile, snapcraft/README.md, snapcraft/crystal-snap-wrapper
This is a part of the effort to migrate the regex engine to PCRE2 (https://github.com/crystal-lang/crystal/issues/12790).
With https://github.com/crystal-lang/crystal/pull/12978, PCRE2 becomes the default engine at which point we should ship libpcre2 in the packages where we distribute the regex library.
That's the bundled tarball and the docker images.
=> Update to libpcre2

docker/Makefile
In a `Makefile` a line of the sort `VAR = VAL  ## comment` makes `VAR` have `VAL ` (note the space). This is documented in the [GNU man of make](https://www.gnu.org/software/make/manual/make.html#Flavors).
> Conversely, if you do not want any whitespace characters at the end of your variable value, you must remember not to put a random comment on the end of the line after some whitespace, such as this:
>
> `dir := /foo/bar    # directory to put the frobs in`
>
> Here the value of the variable dir is ‘/foo/bar    ’ (with four trailing spaces), which was probably not the intention.
=> Bugfix: comments in variables values create spaces

processes/crystal-release.md
The link now points to https://github.com/crystal-lang/crystal/pulls?q=is%3Apr+is%3Amerged+sort%3Aupdated-desc+no%3Amilestone+-label%3Astatus%3Areverted+base%3Amaster+merged%3A%3E%3D2023-01-01 and excludes label `status:reverted`, PRs that were not merged to `master` and old ones.
=> Processes: Narrow down query for PRs without milestone

omnibus/config/software/llvm_bin.rb
Uses the build artifact from #234 with LLVM 15 for building Crystal.
=> Update llvm_bin to LLVM 15

docker/alpine.Dockerfile
Resolves #241 
In the release notes I also noticed they mentioned openssl3 is now the default. I don't think we have to do anything specific related to that, but just pointing it out.
=> Add libxml2 and xz static packages

packages/scripts/install.sh
The canononical URLs contain slashes after each `:` separator. The URLs without slashes redirect to the version with slashes.
This avoids unnecessary redirects and improves resiliency during service disruptions (crystal-lang/crystal#13497).
=> Fix download.opensuse.org URLs with slashes in project path

omnibus/config/software/libffi.rb
Reverts crystal-lang/distribution-scripts#258
This change did not work. For some reason libffi won't build for aarch64. So we must revert this.
=> Revert "Build universal binary for `libffi`"

docker/Makefile, docker/alpine.Dockerfile
I suppose at this point we do not need to build `libgc` ourselves anymore.
We should be able to use the gc package from alpine. It's up to date including the patches that we require for Crystal.
A practical effect of this change is that by default `libgc` will be linked as a dynamic library instead of a static one. This is a subtle change but I don't expect much impact for all practical purposes.
Static linking still works with `--static` of course.
=> Remove building custom `libgc` on alpine, use `gc-dev` package

darwin/Makefile, docs/Dockerfile, docs/Makefile, linux/Dockerfile, linux/Makefile
When constructing a Crystal project, the common practice involves either downloading or cloning the official Git repository for most dependencies. 
It is essential to ensure the ability to test changes against forked repositories. 
I recommend extracting static values into variables for improved flexibility. 
This suggestion involves introducing a `CRYSTAL_REPO` variable with a default value pointing to the official repository.
=> Allow to specify custom CRYSTAL_REPO for forks

darwin/Makefile
pcre2 warning message shows, that it could be compiled against 11.0
```
./src/sljit/sljitExecAllocator.c:154:2: warning: 'pthread_jit_write_protect_np' is only available on macOS 11.0 or newer [-Wunguarded-availability-new]
pthread_jit_write_protect_np(enable_exec);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr/include/pthread.h:588:6: note: 'pthread_jit_write_protect_np' has been marked as being introduced in macOS 11.0 here, but the deployment target is macOS 10.11.0
```
Bump Macos target to 11.0.
PS: It shows on my machine, and does not mean it is the same for other places.
=> MacOS target 11.0

docker/ubuntu.Dockerfile
This makes sure the development package is installed, which includes the pkg-config file (see https://github.com/crystal-lang/crystal/issues/14195#issuecomment-1884786488).
Also, we should stop building our own libgc, which will require installing the library explicitly (#285).
=> Install `libgc-dev` in ubuntu Dockerfile

packages/scripts/install.sh
Fixes a bug in the installer script which lead to choosing `Debian_Unstable` for *every* debian version.
See https://github.com/crystal-lang/distribution-scripts/issues/264#issuecomment-1894793397
=> Fix installer detect Debian version

darwin/Makefile
The empty space preceding the trailing comment is considered part of the value assigned to `CRYSTAL_REPO`.
=> Fix whitespace in Makefile

omnibus/config/software/crystal.rb, omnibus/config/software/shards.rb
I've been investigating [this issue](https://github.com/crystal-lang/crystal/issues/13846) and it's related to the default target triple produced by Crystal during compilation. It seems like in order to fix a [bug](https://github.com/crystal-lang/crystal/issues/1402) back in 2015, we stripped the minimum deployment target from the target triple in this [commit](https://github.com/crystal-lang/crystal/commit/5bbf4d193aba0663b70ee3fbf750ac86b9e966b0). With the release of Xcode 15, a [new linker was introduced](https://developer.apple.com/documentation/xcode-release-notes/xcode-15-release-notes#Linking) and with it came these warning messages. It appears that the new linker is stricter in which target triples it considers valid. Specifically, it looks like the minimum deployment target is …
=> Fix macos triple

processes/scripts/make-crystal-release.sh
In the new changelog format, each release has a level 2 header.
=> Fix extraction of current changelog section

linux/Dockerfile, linux/bundled.dockerfile
We don't need to ship a specially-built version of libgc anymore. This patch drops it from the regular package and moves the build instructions to the bundled package which also includes other necessary libraries.
For this reason we're still keeping `CRYSTAL_CONFIG_LIBRARY_PATH` so that it's still possible to add bundled libraries to that path.
Resolves part of #285
=> Drop building libgc on Linux

linux/Dockerfile
We don't need a specially-built version of libgc anymore and can use the package from Alpine, just like with any other dependency.
Resolves part of https://github.com/crystal-lang/distribution-scripts/issues/285
=> Use libgc from Alpine for building the compiler on Linux

linux/Dockerfile
This workaround is not necessary anymore since shards 0.16.0
=> Drop workaround for shards makefile error

docker/alpine.Dockerfile, linux/Dockerfile
Updates both the linux build environment and the docker images to [AlpineLinux 3.20](https://alpinelinux.org/posts/Alpine-3.20.0-released.html) (from 3.17).
This allows us to upgrade in a follow-up to LLVM 18 which is available in llvm 3.20.
=> Update alpine 3.20

docker/alpine.Dockerfile, docker/ubuntu.Dockerfile, linux/Dockerfile
Updates LLVM to version 18 (from 15) in the build environment as well as the docker images for alpine and ubuntu.
=> Update LLVM 18

docs/aws-config.json
```console
$ make get-website-configuration | tail -n +2 | sed -e 's/1.12.2/${CRYSTAL_VERSION}/g' > aws-config.json
```
=> Apply changes to redirection rules

darwin/Makefile, omnibus/config/software/crystal.rb, omnibus/config/software/llvm_bin.rb, omnibus/config/software/shards.rb
The updated recipes should build on both, x86_64 and arm64 machines.
I have not tested them on x86_64 though.
To fix CI, only arm64 matters.
CI workflow run: https://app.circleci.com/pipelines/github/crystal-lang/crystal/15386/workflows/76ecd816-2187-4eed-aef2-a4959240f1b2/jobs/84572
Resolves #318
=> Update `omnibus` build instructions for aarch64 runner

linux/Dockerfile
Nightly builds are broken because the linux build instructions expect the previous compiler in an old path which was removed in #302. This patch updates to the new path which has been available for years.
=> Fix update bin directory in linux build instructions

packages/test-install-on-docker.sh, packages/test/amazon.bats
Amazon Linux is a popular Linux distribution for which we don't provide explicit packages, but it can use the fallback packages for Fedora. Adding this test ensures we'll notice if anything breaks there.
=> Add installer test for Amazon Linux 2023

packages/scripts/install.sh
Addresses #322.
Currently, the script isn't able to handle generic dnf distros. It is not uncommon for dnf systems to have yum as a symlink for the dnf executable, allowing the script to work by using the RHEL fallback, but for those who don't, the installation just fails.
This PR updates the distro detection strategy to handle generic dnf systems by adding Fedora Rawhide as a fallback if dnf is detected in an unknown distro.
=> Update distro inference strategy to handle dnf based systems

packages/scripts/install.sh
Addresses #322.
Currently, the script uses dnf config-manager to add crystal repo on dnf based systems. The problem with this approach is that config-manager is a plugin for the python implementation of dnf [that will eventually be replaced by the new microdnf implementation](https://fedoraproject.org/wiki/Changes/MajorUpgradeOfMicrodnf#Detailed_Description). Some systems targeted at leaner installations only include microdnf, which is not compatible with the full dnf plugins, making them incompatible with the current strategy.
This PR updates repository installation to manually create [a repo file under /etc/yum.repos.d](https://dnf.readthedocs.io/en/latest/conf_ref.html#description) on dnf systems, just like what is currently done for yum based systems. This change not only enables the …
=> Update dnf installation to be compatible with microdnf

packages/test/centos.bats
CentOS 8 Stream is EOL and the test fails because mirrors are down
=> Drop package install test for CentOS stream

docker/Makefile, docker/alpine-84codes.Dockerfile, docker/ubuntu-84codes.Dockerfile
These docker files are based on the [images from 84codes](https://hub.docker.com/r/84codes/crystal) and add the specific dependencies required for building the compiler (particularly `libllvm`, `libffi`) and are copied from the existing `alpine.Dockerfile` and `ubuntu.Dockerfile`.
This results in up-to-date build images for `linux/arm64` which we're using for Aarch64 CI in https://github.com/crystal-lang/crystal/pull/15007
=> Add Dockerfiles for build images based on 84codes base images

.gitignore
There is no usage of omnibus/shards-darwin-* in the project.
Remove the related record from the `.gitignore`.
=> Remove record from .gitignore

linux/Dockerfile
The original test `[ "$(ldd executable 2>&1 | wc -l)" -eq "1" ]` succeeds if the target file doesn't even exist because in that case `ldd` outputs a single-line error message.
So we're changing the test to check the ELF file type using `readelf` which is available from binutils.
=> Fix check for statically linked binaries

docker/Makefile
We haven't been using deb files for the docker image for a long time.
=> Cleanup unused legacy code

linux/Dockerfile, linux/Makefile, linux/bundled.dockerfile
Docker by default groups log output per step and reduces it (basically just prints the full output if the step failed). This patch adds `--progress=plain` to enable showing the entire log output.
To reduce the overall amount of log output we remove the verbose flag from tar commands. It's not really useful to list all the hundreds of files that get put into the tarball.
=> Use `--progress=plain` docker arg for full log output

linux/Dockerfile
This is a workaround for https://github.com/crystal-lang/shards/pull/667
Resolves https://github.com/crystal-lang/distribution-scripts/issues/330
=> Fix touch `shard.lock` after checkout

linux/Dockerfile
This is required for building manpages from asciidoc.
The darwin package currently doesn't ship crystal or shards manpages, so we don't need this there (yet).
Related: https://github.com/crystal-lang/crystal/issues/15536
=> Install asciidoctor in build environment
