linux/Dockerfile
linux/Makefile

Fixes https://github.com/crystal-lang/crystal/issues/5446

Add package iteration to folder name inside tarball

---

linux/Makefile
omnibus/config/software/shards.rb

CircleCI is ready to be happy about it https://circleci.com/workflow-run/e9144688-50a8-4781-8421-20020e83227d

Update to shards v0.8.1

---

linux/Makefile

Add package url and extract package branding args

---

linux/Makefile

Fixes https://github.com/crystal-lang/crystal/issues/6585
Waiting on build to check packages

Add pkg-config as dependency in linux packages

---

linux/Dockerfile
linux/Makefile

Also remove an unused arg in the dockerfile, unrelated to the other commits.

Improve make documentation

---

linux/Dockerfile

Refs https://github.com/crystal-lang/distribution-scripts/pull/24#discussion_r242534977

Remove unused anymore path

---

linux/Dockerfile

Fixes crystal-lang/crystal#7519

Remove generated docs from linux packages

---

linux/Dockerfile
linux/Makefile

I was doing this anyway, and it works on my machine, could you test if this fixes the CI?

Update linux LLVM to 8, and don't build crystal twice

---

docker/Dockerfile
docker/Makefile

Closes #45
Aligned with https://github.com/crystal-lang/crystal-dist/pull/6
Tested in https://circleci.com/workflow-run/f07d4f85-71d6-4bc0-a0ae-6a14128cfc65

Update docker images to bionic and llvm-8

---

docker/alpine.Dockerfile
docker/ubuntu.Dockerfile

Readline has been removed from stdlib since Crystal 0.32.0

Remove packages for libreadline from dockerfiles

---

linux/files/crystal-wrapper

Ref: https://github.com/crystal-lang/crystal/pull/8364#issuecomment-545092803

Change CRYSTAL_PATH to allow shards to hide std-lib

---

docs/Dockerfile

Depends on the renamed CLI argument from crystal-lang/crystal#9254

Add --json-config-url for docs generation

---

linux/Makefile
omnibus/config/software/shards.rb

Tested at https://circleci.com/workflow-run/050caa0d-7093-4f6d-87b9-e9b8061779ec

Update shards v0.12.0

---

linux/Makefile
omnibus/config/software/shards.rb

update omnibus build instructions to use Makefile otherwise release date was missing on darwin releases.

Update shards to 0.13.0

---

docker/alpine.Dockerfile
linux/Dockerfile

Ref: https://github.com/crystal-lang/distribution-scripts/pull/79/files#r565621160

Restore llvm10-dev in alpine images

---

linux/Dockerfile

Workaround for https://github.com/crystal-lang/crystal/issues/10861

Workaround for shards makefile error

---

linux/Makefile
omnibus/config/software/shards.rb

https://github.com/crystal-lang/shards/releases/tag/v0.15.0

Upgrade to shards 0.15.0

---

packages/README.md

These are the preliminary instructions for pushing changes to OBS.
@beta-ziliani I recommend we/you try this in practice before merging.

Add instructions for OBS builds

---

docs/Makefile

Follow-up to #130 adding another default value to a Makefile argument

Add default value for CRYSTAL_DOCKER_IMAGE

---

linux/Makefile
omnibus/config/software/shards.rb

CI workflow run: https://app.circleci.com/pipelines/github/crystal-lang/crystal/6975/workflows/2b55e93e-835d-4a88-8b2f-0547a6b9c573

Update shards 0.16.0

---

docs/Makefile
docs/aws-config.json

This is a fixup for #161. I forgot to check in the template file.
Also add make recipe to fetch current configuration.

Check in `docs/aws-config.json` template

---

processes/crystal-release.md

* Add preparation step to check docs
* Publish Crystal book version branch
* Remove website latest version update (that's automated now)

Update Crystal release process

---

omnibus/config/software/shards.rb
scripts/update-shards.sh

Ref: https://app.circleci.com/pipelines/github/crystal-lang/crystal/8622/workflows/4f38ac03-7061-4807-b37e-de74926cc9bb/jobs/68359

fixing hash for shards 0.17.0

---

docker/alpine.Dockerfile

Resolves #192
Resolves https://github.com/crystal-lang/crystal/issues/10366
Workflow run: https://app.circleci.com/pipelines/github/crystal-lang/crystal/9341/workflows/7b723987-6800-40b0-beb5-7751bc5d7ef6

Update alpine docker images to 3.16 and llvm 13

---

linux/Makefile
omnibus/config/software/shards.rb

Workflow run: https://app.circleci.com/pipelines/github/crystal-lang/crystal/9918/workflows/153123c4-7e10-4ed1-abc0-756ae798d315

Update shards 0.17.1

---

linux/Makefile
omnibus/config/software/shards.rb

Workflow run: https://app.circleci.com/pipelines/github/crystal-lang/crystal/10710/workflows/35bd3971-6a52-435b-827e-436cab915d00

Update shards 0.17.2

---

packages/test/centos.bats
packages/test/fedora.bats
packages/test/opensuse.bats
packages/test/ubuntu.bats

Removing obsolete OS versions and adding new ones.

Update OS versions for package tests

---

omnibus/config/software/crystal.rb

CI workflow run: https://app.circleci.com/pipelines/github/crystal-lang/crystal/11078/workflows/5c26ce08-5684-4a3d-b6f9-85b8a8007057

Fix CRYSTAL_PATH in omnibus recipe

---

linux/Dockerfile
omnibus/config/software/crystal.rb
omnibus/config/software/pcre2.rb
omnibus/config/software/shards.rb

Build compiler with PCRE2

---

linux/Dockerfile

CI workflow: https://app.circleci.com/pipelines/github/crystal-lang/crystal/11438/workflows/8210bb74-7ded-4816-9914-c32a67c00610
Resolves the Linux part of #229

Update linux build to LLVM 15

---

docker/Makefile
docker/alpine.Dockerfile
docker/ubuntu.Dockerfile

Also updates the base images to alpine 3.17 and ubuntu 22.04
Resolves #206

Update build images to LLVM 15

---

packages/scripts/install.sh

Applies the changes from https://github.com/crystal-lang/crystal-website/pull/451 here

Fix RPM repo public key location

---

packages/scripts/install.sh

This fixes install issues on Fedora 38
https://forum.crystal-lang.org/t/installation-on-fedora-38-fails/5793

Use dnf on fedora

---

omnibus/config/software/libffi.rb

Resolves https://github.com/crystal-lang/crystal/issues/13741

Build universal binary for `libffi`

---

linux/Dockerfile
linux/bundled.dockerfile

Reverts crystal-lang/distribution-scripts#300
Ref https://github.com/crystal-lang/distribution-scripts/issues/285#issuecomment-2110060548

Revert "Drop building libgc on Linux"

---

docker/ubuntu.Dockerfile

Updates the base image for the docker package to Ubuntu 24.04 LTS.

Update ubuntu 24.04

---

packages/test/centos.bats
packages/test/fedora.bats
packages/test/opensuse.bats
packages/test/ubuntu.bats

Adds new versions and drops old ones that have reached end of life.

Update OS versions in bats package tests

---

docker/ubuntu.Dockerfile

Fixup for https://github.com/crystal-lang/distribution-scripts/pull/309

Fix `ld.lld` symlink

---

.circleci/config.yml

Akin to https://github.com/crystal-lang/crystal/pull/15164

Update XCode 15.3.0

---

packages/obs-new-minor.sh
packages/obs-release.sh

Adapts to some of the changes in the package configuration.

Update and fix `obs-release.sh`

---

processes/crystal-release.md

Documenting the process of https://github.com/crystal-lang/crystal/pull/15422, described in https://github.com/crystal-lang/crystal/pull/15414#issuecomment-2639259923

Update instructions for merging release branch into master
